### ISSUE TITLE
🐙🐶功能wish list

### ISSUE THREAD

**Issue by aJiea** [OctoPuppy/Octodog#1]
任务issue学员提交笔记／教程／仓库 ，学员 gitbook

1.开发日志
2.仓库代码
3.教程（重点关注，希望学员的可复用教程输出）
**python班重点：教会半年前的自己**
### 教员手工编织的[迭代项目跟踪表](https://github.com/OpenMindClub/OMOOC2py/issues/11#issuecomment-149749011)包含信息:
- 迭代作品名
  - E文代号
  - 仓库
  - 说明
  - 成员
    - github帐号
    - 仓库
    - 教程
- 课程设置人员信息
### 可提供教员操作
- 项目排名的排行榜
- 点击进去可以看到各个项目的情况,
- 可以issue留言

(仓库教程等原始数据来源不一,教员free提议发表单让大家填写后可跟踪)

**Comment by aJiea** [comment]
### 野心家学员（sherlock）想要功能

1，各项目进度对比。良性竞争。
2，各项目涉及的核心技术，及解决方案，形成案例库。
3，最佳实践分享，包括项目管理方面的经验，思维方面的经验。
4，做项目感觉各自割裂，需继续保持课程热度，比如做个日简报？
5，排名靠前的优秀学员分享，让他们完善gitbook。
6，给大妈的issue太少了，平台可以将自己的发现提给大妈啊，多和他互动。
7，你还可以给项目小组提建议

第1条是mvp，在其基础上进行有效数据筛选。
第4条，感同深受，根据每日数据出日报。

**Comment by junjielizero** [comment]
说一下我想关注的：各个项目进度状况（完成多少，遇到什么困难，待解决的问题有哪些，规划表怎样），代码各成员谁负责写，谁负责管理

补充：尤其关注项目成员超出预期时间内完成代码功能，未能在预期范围内完成代码功能，最终是怎样解决的（何人何时）

**Comment by aJiea** [comment]
想知道小组分工情况，每个组是几个人一起在做一项开发，选最好的用，还是分工合作

**Comment by aJiea** [comment]
- 好些小组找我们问实现xxx的方法，用什么工具
- 没有直接找🐙🐶要方法的，也在日志里说明了当前遇到的问题，其实隔壁的小组已经解决了这个问题

所以🐙🐶[工具推荐](https://github.com/OctoPuppy/Octodog/wiki/%F0%9F%94%A7%E7%AE%B1) 是很有用的一个功能。

请@OctoPuppy/opobs 协助更新🔧箱wiki

**Comment by bambooom** [comment]
下一步的 🐙🐶
https://github.com/OctoPuppy/Octodog/issues/31
