### ISSUE TITLE
资源储备

### ISSUE THREAD

**Issue by bambooom** [OctoPuppy/Octodog#2]
## 团队协作流程
- http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/
- https://help.github.com/articles/github-flow-in-the-browser/
- http://www.ruanyifeng.com/blog/2012/07/git.html
- [廖雪峰github多人协作教程](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000/0013743862006503a1c5bf5a783434581661a3cc2084efa000)
- https://github.com/xpgeng/straypetshelper/issues/1 
## Git & Github
- git命令实操协作 
- [GitHub 漫游指南](https://github.com/phodal/github-roam)
- [廖雪峰Git教程](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000)
- [Git Cheat Sheet](https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf)
- [常用 Git 命令清单](http://www.ruanyifeng.com/blog/2015/12/git-cheat-sheet.html)
- aJiea的[git branch push教程](https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/8wd3_github_branch_push.html)
## 前端相关
- 感谢 谢辉 同学友情提供了一些[前端设置](https://github.com/rayxiehui/OMOOC2py/tree/master/_src/om2py4w/4wex0)
  - 先mark下来~用到时有问题直接联络本人~
- 看到觉得不错的网页可以右键点击"检查" (Chrome浏览器) 直接查看源代码, 最直接的学习方法
- Disqus - 前端加代码即可
- bootstrap - 模板
- http://www.runoob.com/try/bootstrap/layoutit/ 感谢弓箭教练推荐~可视化编辑前端直接下载代码
- 十大前端框架 http://www.sitepoint.com/top-10-front-end-development-frameworks/
- html css js教程汇 http://www.w3schools.com/html/
## UI设计
- [Axure](http://www.axure.com/) 交互原型web&app原型设计
## 后端相关
- [flask](http://flask.pocoo.org/)
  - 课程前面都在用bottle 但是如果想要页面更好看 还需要使用jinjia2 
  - 参考5w使用flask同学代码 也简洁好用 并且自带jinjia2比较好看
  - [flask web development](https://github.com/miguelgrinberg/flasky)
- [docker](https://github.com/docker/docker) (非必需)
- github API 
  - 文档: https://developer.github.com/v3/
  - Python libraries:
    - 我挑了几个库 之后要从需要获得什么数据角度确定怎么选库
    - [PyGithub](https://github.com/PyGithub/PyGithub)
    - [Pygithub3](https://github.com/copitux/python-github3)
    - [github3.py](https://github.com/sigmavirus24/github3.py)
    - [github-flask](http://github-flask.readthedocs.org/en/latest/)
- 技术对接，小赖组的gitbook订阅和互动项目[gitbook monitor](https://wp-lai.gitbooks.io/learn-python/content/team/1208.html)
## 数据可视化
- 待补充
- 一些可视化工具 不确定是否可用 可参考 https://www.zhihu.com/question/19929609
## 会议
- [Webex](http://www.webex.com.cn/) 多人远程会议支持＋屏幕分享
- @scottming 苹果设备录音，直接修改后缀m4a为mp3，上传[QINIU](http://www.qiniu.com/)即可生成录音网址
## 展示用
- [GoAnimate](http://goanimate.com/) 制作卡通小短片~有趣~
- [TermRecord](https://github.com/theonewolf/TermRecord) 命令行视频录制 并可生成html (大妈用的就是这个)

---
## Change Log
- 20151208 +技术对接，产品运营和管理方面工具  @aJiea
- 20151208 +弓箭推荐前端可视化编辑工具 @bambooom
- 20151209 +前端10大框架blog @aJiea
- 20151210 +自己体会教程git branch push  @aJiea
- 20151210 +阮一峰git使用清单 @bambooom
- 20151210 合并git和github两部分 @bambooom

**Comment by bambooom** [comment]
还有啥不错的资源可随时推荐~

**Comment by aJiea** [comment]
### 会议
- [Webex](http://www.webex.com.cn/) 多人远程会议支持＋屏幕分享
- @scottming 苹果设备录音，直接修改后缀m4a为mp3，上传[QINIU](http://www.qiniu.com/)即可生成录音网址

**Comment by aJiea** [comment]
### Runmap工具汇总

[效率沟通类]
- 群友通讯录 http://qun.hk/
- Google group https://groups.google.com/d/msgid/run-map/201512090151396789375%40foxmail.com?utm_medium=email&utm_source=footer

[前端]
- bootstrap GUI 也是drag & drop实现 http://www.layoutit.com/
- 墨刀，10分钟搭建可点击app原型 https://modao.cc/

**Comment by aJiea** [comment]
## API

### API 登陆授权

之前讨论登陆github账号问题，在🐙🐶上的操作同步到github。
虽然现在暂时不需要这个功能，取而用Disqus留言自动询问代之。

![](https://upload.wikimedia.org/wikipedia/commons/3/32/OpenIDvs.Pseudo-AuthenticationusingOAuth.svg)
- [什么是Oauth协议](https://en.wikipedia.org/wiki/OAuth)
- [Github API Oauth支持](https://developer.github.com/v3/)

**Comment by aJiea** [comment]
## aJiea教程
- [UI & Frontend](https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/8wd2_front_end_bootstrap.html)
- [Github branch push](https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/8wd3_github_branch_push.html)

**Comment by bambooom** [comment]
此issue可以放入wiki内继续收集更新~

**Comment by aJiea** [comment]
已经修改，推荐资料是最好［］几个字标签式描述，（）放入链接，便于检索和提高阅读体验
