### ISSUE TITLE
dama 语录

### ISSUE THREAD

**Issue by bambooom** [OctoPuppy/Octodog#29]
内容在这里~
- [x] 输出是更残酷的输入
- [x] 是也乎,(￣▽￣)
- [x] 解决这件事情有三种方法, 你先说说你能想到几种?
- [ ] 嗯哼！
- [ ] single boy single boy single all the time
- [x] KEEP CALM AND …
- [x] 开智 醉点
- [x] 高桥流：
- [x] PPT去死去死
- [x] Kaopulity
- [x] 如何科学的引发关注？这是一种能技
- [x] 初级知识需要对稿件知识深入了解才能真正深入了解。
- [x] 以最小代价解决问题！
- [x] 路径依赖&习得性无助
- [ ] 有编程思维的人很难忽视信息。
- [x] 所有东西都能教授，但！求知欲和学习能力除外。
- [ ] 开智五品: 勤奋.专注.持久.创意.良善
- [ ] 与42有关的一切
- [x] Life's Pathetic, go Pythonic! 人生苦短, Python 当歌!
- [ ] BGM
- [ ] 不仅学编程
    更是练思维
- [x] 汇同开智人
  同侪并升级
- [x] **编程思维**的培养必须_要_编程  
  **靠谱行为**的基础只能是靠谱  
  **提问**是获得技能的**唯一起点**  
  教练价值**源自**你_真诚_的行为  
- [ ]  **合意阻滞**是学习的**最佳动力** (这句话暂时木有)

aJiea补充
- [x] 只有自己锻炼出来的肌肉才能形成自己的马甲线，要不我把我的马甲线借给你吧，这没法借，亲～
- [x] 这又是视而不见，亲～
- [x] 多做多错，少做少错，不做不错

**Comment by ZoomQuiet** [comment]
大炸弹哪,,,,
妳如此泄的底儿,好嘛!?

2015-12-29 19:47 GMT+08:00 Bamboo notifications@github.com:

> 内容在这里~
> 
> 是也乎,(￣▽￣)

...

**Comment by bambooom** [comment]
@ZoomQuiet 临时用一用issue........orz

**Comment by sunnyhuang42** [comment]
> 合意阻滞是学习的最佳动力 (这句话暂时木有)

这句话如果没记错的话，好像是在开学典礼的时候提到过，当时阳老听到时还说「怎么翻译成 合意阻滞 了呢，应该是 必要难度 啊！」哈哈~

> 解决这件事情有三种方法, 你先说说你能想到几种?

这个是在10w 还是9w 学员连线提问的时候常说的

> single boy single boy single all the time

上周课程里的吧，不记得唱没唱了……

**Comment by bambooom** [comment]
完成~
