### ISSUE TITLE
各组仓库地址更新及补全

### ISSUE THREAD

**Issue by bambooom** [OctoPuppy/Octodog#4]
https://github.com/OpenMindClub/OMOOC2py/issues/11
先谢谢素封教练已手动完成大部分 此处进行更新及补全
1. [爱搭配 iMatch](https://github.com/yondjune/iMatch)
   - @JeremiahZhang 负责 app aka
   - @whb1990111 负责支付接口
   - @simple2source 负责web框架
   - @yondjune 负责web框架
   - @wp-lai 观察员
2. [走图 RUNMAP](https://github.com/Run-map/RUNMAP)
   - @shawn0lee0 服务器后台
   - @Lcking WEB架构+优化
   - @bingosummer 服务器后台
   - @wwshen 用户行为分析
   - @Acural 原型设计
   - @qingquan0083 友情测试
   - @aJiea (植入观察员)
3. [拆书智囊 RIA Brain-truster](https://github.com/Wangqiaoyang/RIA-Brain-truster/)
4. [A股筛选器 SPR (Stock Pickup and Reminding)](https://github.com/sherlockhoatszx/Stock_Pickup_and_Reminding)
   - @sherlockhoatszx
   - @veratulips
   - @siyuany
   - @jasonycliu  
   - @bambooom (植入观察员)
5. [个人照片备份整理程序 PhotoxOrganizer](https://github.com/penguinjing/PhotoxOrganizer)
6. [记着买 Jizhemai](https://github.com/ivanlau/jizhemai/)
   - @ivanlau
   - @rayxiehui
   - @Langp618
   - @bambooom (植入观察员)
7. [情绪日记](https://github.com/imoodmap/imoodmapGroup)
   - @WhaleChen
   - @zoejane
   - @xiaoyuer
   - @wwshen
   - @haruhi99
   - @wp-lai
8. [带它回家 Stray Pets Helper(SPH)](https://github.com/xpgeng/straypetshelper)
   - @xpgeng
   - @huijuannan (前端+植入观察员)
   - @tiezipy
9. [网络遗书 whenmgone](https://github.com/liangchaob/whenmgone)
10. [社群参与者数据库 communitydata]
11. [阅读的狩猎 Hunting for Great Books](https://github.com/junjielizero/Hunting-for-Great-Books)
    - @junjielizero
    - @janice-lu-zeng
12. [买房推荐系统 House Recommend System](https://github.com/liangpeili/housebuy)
    - @yangshaoshun
    - @hongzhih
    - @dyelaine
13. [章鱼狗 Octodog](https://github.com/OctoPuppy/Octodog)
    - @bambooom 开发
    - @hysic 前端
    - @aJiea UI
    - @huijuannan 观察
    - @Scott 观察
    - @4plus-ma 产品运营&观察
    - @zero 客串观察
14. [麦宝 MIPE](https://github.com/wp-lai/mipe)
    - @wp-lai 主程
    - @sunoonlee 主程
    - @JeremiahZhang 观察员
    - @bambooom 观察员
    - @zoejane 观察员 
15. [习惯养成 less habit](https://github.com/Cen74/less-habit)
    - @Cen74 开发
    - @BaiL UI+开发
    - @soul2867 UI
    - @sunoonlee 观察员
## Changelog
- 20151208 创建编辑 @bambooom
- 20151208 更新章鱼狗仓库 @aJiea 
- 20151208 更新A股筛选器仓库地址 @bambooom
- 20151208 更新部分成员信息&狗仔队分布 @aJiea
- 20151209 更新情绪日记仓库地址及成员信息&爱搭配成员信息 @bambooom
- 20151209 添加麦宝项目及成员信息 @bambooom
- 20151210 更新买房推荐仓库地址 @bambooom
- 20151210 更新章鱼狗仓库地址 @bambooom
- 20151211 更新走图仓库地址及成员信息 @bambooom
- 20151211 更新麦宝仓库地址 @bambooom
- 20151211 添加习惯养成小组项目信息 @bambooom

**Comment by yondjune** [comment]
https://github.com/yondjune/iMatch/issues/1

https://github.com/yondjune/iMatch/issues/2

**Comment by bambooom** [comment]
此issue可以放入wiki内继续更新~

**Comment by yondjune** [comment]
搬去wiki之后就不能留言了？

**Comment by aJiea** [comment]
wiki不支持issue这种bbs似功能。。。

我们的平台会有一个吐槽处，尽情期待升级 http://projboard.sinaapp.com/#

**Comment by sunoonlee** [comment]
#### 补充两则信息
- No.14 麦宝 英文名为：MIPE
- 漏了一个项目：
  - 名称：习惯养成
  - 英文名：less habit
  - [仓库](https://github.com/Cen74/less-habit)
  - 说明：https://github.com/Cen74/OMOOC2py/issues/2
  - 成员：@ Cen74(开发), @ BaiL(UI+开发), @ soul2867(UI)，@ sunoonlee(观察员)

**Comment by bambooom** [comment]
@sunoonlee 多谢!!!

**Comment by bambooom** [comment]
见wiki~
