### ISSUE TITLE
8w讨论

### ISSUE THREAD

**Issue by aJiea** [OctoPuppy/Octodog#5]
### 适合MVP的UI设计和调整

(上传图片失败，用链接展示)

[Home Page](http://7xnvqn.com1.z0.glb.clouddn.com/2.pic_hd.jpg)

[留言板](http://7xnvqn.com1.z0.glb.clouddn.com/1.pic_hd.jpg)

@hysic 
－ 上面&左侧导航条固定，变的只有中间灰色部分内容
－ 8w MVP左侧导航条🔍［搜索］功能（非必需）
－ 点击项目标题（SPR）直接跳到介绍页面＋留言板
－ 点击项目下方［Member］［Tutorial］功能（非必需）
### 留言功能讨论

用Disqus还是用日记本记事功能完成？先不管Notification
- [disqus] 每个小组的页面留言是否是独立的
- disqus镶入后显示的位置

**Comment by bambooom** [comment]
### 有关Disqus插入~
- 其实是前端插入代码即可
- 正好同学们基本都有disqus账户了, 还是用Disqus方便
- 省去使用数据库麻烦

**Comment by bambooom** [comment]
此issue应该和技术讨论区合并~~
