### ISSUE TITLE
8wd3问卷，请补充

### ISSUE THREAD

**Issue by aJiea** [OctoPuppy/Octodog#6]
8wd2给项目发起人的问卷
- 组名
- w8所遇到的问题
  1. 
  2. 
  3. 
- 对应解决方案
  1. 
  2. 
  3. 
- 最想知道关于其他小组的什么情况
  1. 
  2. 
  3.

**Comment by WhaleChen** [comment]
## imoodmap 小组汇报
- 组名：imoodmap 情绪日记小分队
- w8遇到的问题：
  
  i. 任务明确度不高
  ii. 人员投入总时间不足，个人时间安排有困难
  iii. 核心能技需要提升：主要是发起人代码能力和项目规划能力有限。
  iv. git branch 的使用团体还是不熟悉
- 解决：
  i 细化目标和初衷，简化任务
  ii 使用 github 和tower ，不过效果目前看还是有限
  iii 核心技能通过模仿大牛和其他团队提升 拉@wp-lai 入伙 同时 加入 Octodog 当观察员，感谢！
  Iv 学习文档，多建立branch和习惯化
- 最想知道其他团队的情况：
  i 团队如何协作和分工
  ii 如何激励成员去共同完成一个任务
  iii 没有大牛的团队如何预期项目进度
  
  其他参考：[imoodmap 第一周项目阶段评估和任务重塑](https://whalechen.gitbooks.io/omooc2py/content/imoodmap/20151209review.html)
