### ISSUE TITLE
各团队开发规划(资料收集，无版权，纯属学习)

### ISSUE THREAD

**Issue by aJiea** [OctoPuppy/Octodog#8]
## Runmap版本规划：
- 第1周：MVP
  - DAY1：功能精简、搭平台、熟悉API
  - [交互效果V1.0](https://modao.cc/app/wZtUeShfg7Q8DGUeembZ)
  - ![](http://i5.tietuku.com/2de2658477fdfc2bs.png)![](http://i5.tietuku.com/cf4ddc327dab57cds.png)
  - DAY2：[ ] MVP_0.1 实现CLI地址、坐标解析，该结构可适用于后期api调用
  - DAY3：--2015年12月9日
    - [x] 交互页面V1.1初稿、说明文档（墨刀、layoutit.com）
  - [x] web架构MVP
    - [ ] 本地运行版本实现：框架：flask
    - []云平台选择:云os/sinasae/七牛 原则：优先考虑国内服务器。
    - []公网版本MVP
      - []通过域名访问
    - []获取ip.gps 通过webapi解析
  - [ ]服务端后台MVP
    - [][数据表属性字段定义完善](http://developer.baidu.com/map/index.php?title=yingyan/api/entity)
    - []上传本地gps信息并解析
    - []可查询历史轨迹
  - DAY4：
    - []页面定稿&文档
  - []Web + html +(js)接口融合
  - []优化、测试
  - DAY5/6：核心功能模块开发、优化
    - []后台轨迹实时监控存储
  - []后台历史轨迹查询
  - []时间戳
  - []多轨迹统计分析（轨迹活跃度|时间）
  - DAY7：独立模块内测、迭代

成员要求：
- WEB架构+优化：[@Lcking](https://github.com/Lcking)
  - 服务器后台:[@bingosummer](https://github.com/bingosummer),[@shawn0lee0](https://github.com/shawn0lee0/RUNMAP)，[@Lcking](https://github.com/Lcking)
  - 观察、测试：
    - 原型设计分析：[@Acural](https://github.com/Acural)，[@Lcking](https://github.com/Lcking)
  - 用户行为分析：[@wwshen](https://github.com/wwshen)，[植入观察@aJiea](https://github.com/aJiea)
  - 观察员：开发过程中所有相关工作文档整理、api接口梳理、测试笔记，知识管理（能够相关联起来）
  - 测试：全员参与|友情测试@qingquan0083
  - 程序猿鼓励师：[@wwshen](https://github.com/wwshen)，@aJiea，@shawn0lee0
  - 有余力：思考web与ios/android GPS模块调用

摘自[Runmap Google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/run-map/vENbSmG1hCs/1HPAZEoYCQAJ)

**Comment by scottming** [comment]
# 合智项目开发日志
- [个人照片备份整理程序 ](https://github.com/penguinjing/PhotoxOrganizer/issues/1) 开发日志在issues最下方。
- [A股筛选器](https://github.com/sherlockhoatszx/Stock_Pickup_and_Reminding) 暂无开发日志，README.MD 有功能完成进展。
- [走图版本规划](https://github.com/shawn0lee0/RUNMAP#版本规划),很详细，不过版本规划那个地方的 Markdown 写错了，正确写法是`- [ ] 文字`，文字前面有个空格。
- [【阅读的狩猎】项目说明](https://github.com/junjielizero/junjielizero/issues/2) ，暂无开发日志。
- [带它回家 issues](https://github.com/xpgeng/straypetshelper/issues/3) ，非常详细的开发日志。
- [社群参与者数据库项目说明](https://jameszhou89.gitbooks.io/moocpy2/content/project_proposal.html)、[项目启动和规划 | MOOC Python勇猛精进](https://jameszhou89.gitbooks.io/moocpy2/content/project%20on%20the%20run.html) 、[Project proposal | MOOC Python勇猛精进](https://jameszhou89.gitbooks.io/moocpy2/content/project_proposal.html) ，暂无开发日志。
- [拆书智囊](https://github.com/Wangqiaoyang/RIA-Brain-truster/issues/1) ，暂无开发日志。
- [网络遗书项目说明](https://liangchaob.gitbooks.io/omooc2py/content/DevBlogs/w7.html) 从最小原型开始，有关于项目的开发日志，另外，这位同学是按周来写的个人日志，关于项目开发日志，还没看到。
- [买房推荐系统](https://github.com/OpenMindClub/OMOOC2py/issues/96#issuecomment-160867279) ，暂没看到开发日志。
- [iMatch 项目简介](https://github.com/yondjune/iMatch/issues/1) 爱搭配，项目在搜集资料阶段。
- [记着买项目概述 · Issue #1 · ivanlau/jizhemai](https://github.com/ivanlau/jizhemai/issues/1) 有项目简介，暂无开发日志。
- [[8w~迭代作品] 项目公示 · Issue #96 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/96#issuecomment-161320352) 梦想的秘密花园，还在构思阶段。
- [懒人SEOCMS](https://github.com/OpenMindClub/OMOOC2py/issues/96#issuecomment-161506416) 暂无开发日志。
- [我想长大项目说明](https://github.com/picklecai/OMOOC2py/issues/1) ，项目进展在最下方。
- [情绪日记开发日志](https://github.com/imoodmap/imoodmapGroup/issues/2)，充满了正能量啊。
- [习惯养成项目说明](https://github.com/Cen74/OMOOC2py/issues/2)
- [P助手项目说明](https://github.com/OpenMindClub/OMOOC2py/issues/96#issuecomment-161222915)
- [麦宝项目进展](https://wp-lai.gitbooks.io/learn-python/content/team/1208.html)

**Comment by bambooom** [comment]
资料收集可收入wiki~
